/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ShortsRouteImport } from './routes/shorts'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SchedulerRouteImport } from './routes/scheduler'
import { Route as LibraryRouteImport } from './routes/library'
import { Route as InstallRouteImport } from './routes/install'
import { Route as GeneratorRouteImport } from './routes/generator'
import { Route as ClipMineRouteImport } from './routes/clip-mine'
import { Route as IndexRouteImport } from './routes/index'

const ShortsRoute = ShortsRouteImport.update({
  id: '/shorts',
  path: '/shorts',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SchedulerRoute = SchedulerRouteImport.update({
  id: '/scheduler',
  path: '/scheduler',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryRoute = LibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => rootRouteImport,
} as any)
const InstallRoute = InstallRouteImport.update({
  id: '/install',
  path: '/install',
  getParentRoute: () => rootRouteImport,
} as any)
const GeneratorRoute = GeneratorRouteImport.update({
  id: '/generator',
  path: '/generator',
  getParentRoute: () => rootRouteImport,
} as any)
const ClipMineRoute = ClipMineRouteImport.update({
  id: '/clip-mine',
  path: '/clip-mine',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/clip-mine': typeof ClipMineRoute
  '/generator': typeof GeneratorRoute
  '/install': typeof InstallRoute
  '/library': typeof LibraryRoute
  '/scheduler': typeof SchedulerRoute
  '/settings': typeof SettingsRoute
  '/shorts': typeof ShortsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/clip-mine': typeof ClipMineRoute
  '/generator': typeof GeneratorRoute
  '/install': typeof InstallRoute
  '/library': typeof LibraryRoute
  '/scheduler': typeof SchedulerRoute
  '/settings': typeof SettingsRoute
  '/shorts': typeof ShortsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/clip-mine': typeof ClipMineRoute
  '/generator': typeof GeneratorRoute
  '/install': typeof InstallRoute
  '/library': typeof LibraryRoute
  '/scheduler': typeof SchedulerRoute
  '/settings': typeof SettingsRoute
  '/shorts': typeof ShortsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/clip-mine'
    | '/generator'
    | '/install'
    | '/library'
    | '/scheduler'
    | '/settings'
    | '/shorts'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/clip-mine'
    | '/generator'
    | '/install'
    | '/library'
    | '/scheduler'
    | '/settings'
    | '/shorts'
  id:
    | '__root__'
    | '/'
    | '/clip-mine'
    | '/generator'
    | '/install'
    | '/library'
    | '/scheduler'
    | '/settings'
    | '/shorts'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ClipMineRoute: typeof ClipMineRoute
  GeneratorRoute: typeof GeneratorRoute
  InstallRoute: typeof InstallRoute
  LibraryRoute: typeof LibraryRoute
  SchedulerRoute: typeof SchedulerRoute
  SettingsRoute: typeof SettingsRoute
  ShortsRoute: typeof ShortsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/shorts': {
      id: '/shorts'
      path: '/shorts'
      fullPath: '/shorts'
      preLoaderRoute: typeof ShortsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scheduler': {
      id: '/scheduler'
      path: '/scheduler'
      fullPath: '/scheduler'
      preLoaderRoute: typeof SchedulerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library': {
      id: '/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof LibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/install': {
      id: '/install'
      path: '/install'
      fullPath: '/install'
      preLoaderRoute: typeof InstallRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/generator': {
      id: '/generator'
      path: '/generator'
      fullPath: '/generator'
      preLoaderRoute: typeof GeneratorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clip-mine': {
      id: '/clip-mine'
      path: '/clip-mine'
      fullPath: '/clip-mine'
      preLoaderRoute: typeof ClipMineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ClipMineRoute: ClipMineRoute,
  GeneratorRoute: GeneratorRoute,
  InstallRoute: InstallRoute,
  LibraryRoute: LibraryRoute,
  SchedulerRoute: SchedulerRoute,
  SettingsRoute: SettingsRoute,
  ShortsRoute: ShortsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
